### ISSUE TITLE
Question: disconnect behaviour

### ISSUE THREAD

**Issue by luiscurini** [googlecast/CastAndroidTvReceiver#1]
Hi! 

I implemented CastConnect in my app and it works quite well however we are encountering a behaviour that also this example has. Once you're casting a Video and it's playing on the Android TV app, if you click again on Casting icon on the mobile device and click on Stop casting, the mobile app disconnects successfully but the Android TV app continues playing. Is there a way to pause/stop the video on the Android TV app once this happens?

**Comment by jtromo** [comment]
This is expected behavior. 

For your use case, please try to set the following flag on your CastOptions to `true` on the Android sender: https://developers.google.com/android/reference/com/google/android/gms/cast/framework/CastOptions#getStopReceiverApplicationWhenEndingSession()

Which senders are you currently seeing this on?

**Comment by vpunjabi** [comment]
Please reopen if this is still an issue.
